---

## recommended settings
- name: modify memlock parameter
  pam_limits: domain=cassandra limit_type=- limit_item=memlock value=unlimited

- name: modify nofile parameter
  pam_limits: domain=cassandra limit_type=- limit_item=nofile value=100000

- name: modify nproc parameter
  pam_limits: domain=cassandra limit_type=- limit_item=nproc value=32768

- name: modify as parameter
  pam_limits: domain=cassandra limit_type=- limit_item=as value=unlimited

- name: install jemalloc library
  apt: pkg=libjemalloc1 state=latest update_cache=yes force=yes

- name: swap - disable swap
  command: swapoff --all
  ignore_errors: yes
  become: yes

- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent
  become: yes

- name: Create data folder
  when: "{{ data_file_directories is defined }}"
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ data_file_directories }}"
  become: yes

## install cassandra
- name: Add cassandra deb repository
  apt_repository:
    repo: 'deb http://www.apache.org/dist/cassandra/debian {{ cassandra_series_version }} main'
    state: present

- name: Install cassandra repository keys
  apt_key:
    url: 'https://www.apache.org/dist/cassandra/KEYS'
    state: present

- name: install cassandra packages
  apt:
    pkg: cassandra
    state: latest
    update_cache: yes
    force: yes
  register: cassandra_exists

## initialize cluster
- name: Stop service
  service: name=cassandra state=stopped

- file:
    path: "{{ cassandra_home }}/commitlog"
    state: absent
  become: true
  when: cassandra_exists.changed

- file:
    path: "{{ cassandra_home }}/saved_caches"
    state: absent
  become: true
  when: cassandra_exists.changed

- file:
    path: "{{ cassandra_home }}/data/system"
    state: absent
  become: true
  when: cassandra_exists.changed

- debug:
    msg: "Cassandra {{seed_provider_seeds}} {{listen_address}}"

- name: copy cassandra conf
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/cassandra.yaml
    backup: yes

- name: copy cassandra env
  template:
    src: cassandra-env.sh.j2
    dest: /etc/cassandra/cassandra-env.sh
    mode: '0644'
    backup: yes

- name: restart cassandra
  command: echo "cassandra configuration changed"
  notify: restart cassandra
  
